### ISSUE TITLE
thermochem error for T = 0K

### ISSUE THREAD

**Issue by swheele2** [QChASM/AaronTools.py#12]
We seem to be catching T = 0K as a special case, but then treating it incorrectly.
At 0K, H and G are equal to E + ZPVE, not E.

(To convince yourself of this, compare the output from grabThermo.py at T = 0 and T = 0.000001)

**Comment by ajs99778** [comment]
Fixed. If you intend for me to fix things, please assign the issue to me so I get a notification.

**Comment by swheele2** [comment]
Thanks. I mainly submitted the issue as a reminder for me to look at it when I had some time, but figured you would probably see it and fix it in the meantime.

Steven

**Comment by ajs99778** [comment]
you can also assign issues to yourself
