### ISSUE TITLE
write orca SMD

### ISSUE THREAD

**Issue by joegair** [QChASM/AaronTools.py#13]
When I use `solvent = ImplicitSolvent("SMD", "water")` to write an ORCA input file, the resulting file contains

```
! CPCM(water)
%cpcm
    smd    true
end
```

This input raises an error in ORCA 5.0.3
```
	 Error: Missing keyword in CPCM block
	 Missing keyword : SMDsolvent
```

A functional input looks like
```
! CPCM
%cpcm
    smd    true
    SMDsolvent "water"
end
```

It is fine to work around this by adding `ORCA_BLOCKS={'cpcm':['SMDsolvent "water"']}` to 'geom.write'. It would be nice if this was built in.

**Comment by ajs99778** [comment]
Thanks for reporting this, I appreciate all the recent feedback. This will be fixed soon.

**Comment by ajs99778** [comment]
fixed
