### ISSUE TITLE
problem parsing

### ISSUE THREAD

**Issue by joegair** [QChASM/AaronTools.py#15]
AaronTools raises an error when reading this file.

[gemfi_beta_uTS_22.out.zip](https://github.com/QChASM/AaronTools.py/files/11132154/gemfi_beta_uTS_22.out.zip)

`fr = FileReader(path, get_all=True, just_geom=False)`

`ValueError: could not convert string to float: 'SPECTRUM'`

For what it is worth, this closely related job is read without problems.
[gemfi_beta_uTS_21.out.zip](https://github.com/QChASM/AaronTools.py/files/11132158/gemfi_beta_uTS_21.out.zip)

Given that the `ValueError` looks related to the frequencies, it is notable that `gemfi_beta_uTS_22.out` has two imaginary frequencies.

**Comment by ajs99778** [comment]
This is indeed related to the frequencies. The file with the error prints data for a hybrid hessian, including frequencies and spectra data but not normal mode displacements. Our parser cannot handle this. I'll try to find a workaround.

**Comment by ajs99778** [comment]
fixed
