### ISSUE TITLE
B2PLYP-D3 = B2PLYPD3

### ISSUE THREAD

**Issue by joegair** [QChASM/AaronTools.py#16]
the hyphenated version is in ORCA. Would be nice if they were both accessible via the same keyword.

**Comment by ajs99778** [comment]
Thanks for reporting this. Apparently, B2PLYP-D3 was a valid keyword in ORCA 4 (it's in their manual). I've removed it from our list. I'll go back and make sure the rest of them are still valid at some point.

I've added aliases for DSD-PBEP86 and a couple other double hybrids for ORCA and Gaussian keywords.
