### ISSUE TITLE
Small bug in SubmitProcess

### ISSUE THREAD

**Issue by rlaplaza** [QChASM/AaronTools.py#2]
Hello,

Thanks for developing this library. I, for one, am excited to see Aaron2 come along.

I think that there is a small error in SubmitProcess for SLURM:
```
        elif QUEUE_TYPE == "SLURM":
            args = ["sbatch", "<", job_file]

```
the "<" should be removed, as far as I known, because the submission command is simply sbatch job_file. At least this is what works in my cluster at the moment.

Thanks in advance!

**Comment by ajs99778** [comment]
Thanks, I've applied your fix. `sbatch` can read the job file from standard input, which the "<" was supposed to set to be the job file. However, the python code we're using to run system commands has its own method for setting standard input.
