### ISSUE TITLE
Loading Gaussian16 Scan

### ISSUE THREAD

**Issue by Cdc95** [QChASM/AaronTools.py#5]
I am not entirely sure if this is a bug or not but when I load a gaussian 16 scan file it loads "all" of the structures and not just the "optimized" ones along the path (so a 72 point scan ends up having over 500 structures). Is there anyway to fix this? (ChimeraX1.4 and most recent SEQCROW on mac)

Thanks a bunch!

**Comment by ajs99778** [comment]
I've moved this to AaronTools, as that's the module we use to parse Gaussian output files. I think a straightforward way for us to fix this would be to add the option to only save structures for iterations where all the convergence criteria are met.

I'm trying to work on my dissertation right now, so I won't be able to get to this for a while. If someone else wants to take a stab at it, look at getting this function:
https://github.com/QChASM/AaronTools.py/blob/9f152119663806c2c5a6d27afb23bc8e0c46bcfa/fileIO.py#L2262
 to detect whether the coordinates are being scanned. Then check if all `FileReader.other["gradient"]` values are `True` when we go to store another structures, should be near
https://github.com/QChASM/AaronTools.py/blob/9f152119663806c2c5a6d27afb23bc8e0c46bcfa/fileIO.py#L2368 @landreola @swheele2

**Comment by swheele2** [comment]
@landreola will take care of it.

**Comment by ajs99778** [comment]
@landreola added this. It is in SEQCROW 1.4.4.
